name: ReportPlus
version: ${project.buildVer}
main: me.xbones.reportplus.spigot.ReportPlus
authors: [xBones,Fernthedev]
api-version: 1.14
softdepend:
  - Vault
  - TitleAPI
commands:
  report:
    description: Report players to staff in the server!
    usage: /report <Message>
    aliases:
      - rpgui
      - reportgui
      - spigotreport
  txtcmd:
    description: Add a command to the discord bot that says the text you specify!
    usage: /txtcmd <Command> <Text>
  cmdcmd:
    description: Add a command to the discord bot that says the text you specify!
    usage: /cmdcmd <Command> <Command to be executed>
  reports:
    description: View recent updates!
    usage: /reports
  reportplus:
    description: View version of the ReportPlus plugin!
    usage: /reportplus
    aliases: [rp]